
package hospital;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author SBS
 */
public class login extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
   static String nomD=null;
   static String prenomD=null;
   static String nomP=null;
   static String prenomP=null;
    
    /**
     * Creates new form login
     */
    
    
    public login() {
        initComponents();
        centerFrameOnScreen();
    }
  
    private void centerFrameOnScreen() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int centerX = (int) screenSize.getWidth() / 2;
        int centerY = (int) screenSize.getHeight() / 2;

        int frameWidth = this.getSize().width;
        int frameHeight = this.getSize().height;

        int setLocationX = centerX - frameWidth / 2;
        int setLocationY = centerY - frameHeight / 2;

        this.setLocation(setLocationX, setLocationY);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkpassword = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        SignIn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 230, 28));

        jLabel1.setText("E-mail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        checkpassword.setText("check password");
        checkpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(checkpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        loginButton.setBackground(new java.awt.Color(51, 153, 255));
        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setText("login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 100, 30));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 228, 30));

        SignIn.setBackground(new java.awt.Color(51, 153, 255));
        SignIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SignIn.setText("Sign In");
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });
        getContentPane().add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\SBS\\Documents\\NetBeansProjects\\Hospital\\src\\hospital\\hospital image.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkpasswordActionPerformed

        if(checkpassword.isSelected())
        {
            password.setEchoChar((char)0);
        }
        else {
            password.setEchoChar('*');
        }

    }//GEN-LAST:event_checkpasswordActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
         if (!(email.getText().equals("")) || !(password.getText().equals("")) ){


            
            
            
            try {
                con =connexion.getConnect();
                ps =con.prepareStatement("select * from docteur ");
                rs =ps.executeQuery();

                String mailD=null;
                String mdpD=null;
                while(rs.next()){
                    
                    mailD =rs.getString("email");
                    mdpD =rs.getString("mdp");
                    
                    if((mailD.equals(email.getText()))&&(mdpD.equals(password.getText()))){
                   
                    nomD =rs.getString("nom");
                    prenomD =rs.getString("prenom");
                    new  medecin().setVisible(true);
                    this.setVisible(false);
                    
                }
                }
                
                
                
                ps =con.prepareStatement("select * from patient ");
                rs =ps.executeQuery();

                String mailP=null;
                String mdpP=null;
                while(rs.next()){
                    
                    mailP =rs.getString("email");
                    mdpP =rs.getString("mdp");
                    
                    if((mailP.equals(email.getText()))&&(mdpP.equals(password.getText()))){
                   
                        nomP =rs.getString("nom");
                    prenomP =rs.getString("prenom");
                    new  patient().setVisible(true);
                    this.setVisible(false);
                    
                }
                }
                
                
                
            } catch (Exception e) {
                e.getMessage();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Missing information");

            

        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
        
        new SignIn().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignIn;
    private javax.swing.JCheckBox checkpassword;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables

    String getDoctor() {
                  return nomD+" "+prenomD;
                   
             }
    String getPatient() {
                  return nomP+" "+prenomP;
                   
             }
}
