/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;

/**
 *
 * @author SBS
 */
public class monDocteur extends javax.swing.JFrame {
 login l;
    Connection con=null;
    /**
     * Creates new form monDocteur
     */
    public monDocteur() {
        initComponents();
        centerFrameOnScreen();
        l=new login();
            String nom=l.getPatient();
            patientNom.setText(nom);
            displayDoctorData();    
    }
private void centerFrameOnScreen() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int centerX = (int) screenSize.getWidth() / 2;
        int centerY = (int) screenSize.getHeight() / 2;

        int frameWidth = this.getSize().width;
        int frameHeight = this.getSize().height;

        int setLocationX = centerX - frameWidth / 2;
        int setLocationY = centerY - frameHeight / 2;

        this.setLocation(setLocationX, setLocationY);
    }
private void displayDoctorData() {
    try {
        l = new login();
        String nom = l.getPatient();
        String[] words = nom.split("\\s+");
        String firstWord = words[0];

        con = (Connection) connexion.getConnect();
        
        // Query to get doctorName from patient table
        String sql1 = "SELECT mondoc FROM patient WHERE nom = ?";
        try (PreparedStatement statement1 = (PreparedStatement) con.prepareStatement(sql1)) {
            statement1.setString(1, firstWord);
            try (ResultSet resultSet1 = (ResultSet) statement1.executeQuery()) {
                if (resultSet1.next()) {
                    String doctorName = resultSet1.getString("mondoc");
                    String[] word = doctorName.split("\\s+");
                    String firstName = word[0];
                    // Query to get doctor information from docteur table
                    String sql = "SELECT nom, prenom, adresse, email FROM docteur WHERE nom = ?";
                    try (PreparedStatement statement = (PreparedStatement) con.prepareStatement(sql)) {
                        statement.setString(1, firstName);
                        try (ResultSet resultSet = (ResultSet) statement.executeQuery()) {
                            if (resultSet.next()) {
                                String nom1 = resultSet.getString("nom");
                                String prenom = resultSet.getString("prenom");
                                String adresse = resultSet.getString("adresse");
                                String email = resultSet.getString("email");

                                nomd.setText(nom1);
                                prenomd.setText(prenom);
                                adressed.setText(adresse);
                                emaild.setText(email);
                            } else {
                                // Handle the case when the doctor is not found
                                System.out.println("Doctor not found with name: " + doctorName);
                            }
                        }
                    }
                } else {
                    // Handle the case when no mondoc is found for the given patient name
                    System.out.println("No mondoc found for patient name: " + firstWord);
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientNom = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomd = new javax.swing.JTextField();
        prenomd = new javax.swing.JTextField();
        adressed = new javax.swing.JTextField();
        emaild = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientNom.setBackground(new java.awt.Color(204, 204, 204));
        patientNom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        patientNom.setForeground(new java.awt.Color(0, 0, 255));
        patientNom.setText("patient");
        getContentPane().add(patientNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 10, 140, 38));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Rendez_vous");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/turn-left.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 24, 32));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Mon Docteur");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 30));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("Quitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 30));

        jLabel3.setText("Nom :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel4.setText("Prenom :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel5.setText("Adresse :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel6.setText("E-mail :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        nomd.setEditable(false);
        getContentPane().add(nomd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 100, -1));

        prenomd.setEditable(false);
        getContentPane().add(prenomd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 100, -1));

        adressed.setEditable(false);
        getContentPane().add(adressed, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 100, -1));

        emaild.setEditable(false);
        getContentPane().add(emaild, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 100, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("Acceuil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/pat.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new rendezvous().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        new patient().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(monDocteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(monDocteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(monDocteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(monDocteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new monDocteur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adressed;
    private javax.swing.JTextField emaild;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomd;
    private javax.swing.JLabel patientNom;
    private javax.swing.JTextField prenomd;
    // End of variables declaration//GEN-END:variables
}
