/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SBS
 */
public class signInPatient extends javax.swing.JFrame {

    Connection con=null;
    /**
     * Creates new form signInPatient
     */
    public signInPatient() {
        initComponents();
        centerFrameOnScreen();
    }
private void centerFrameOnScreen() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int centerX = (int) screenSize.getWidth() / 2;
        int centerY = (int) screenSize.getHeight() / 2;

        int frameWidth = this.getSize().width;
        int frameHeight = this.getSize().height;

        int setLocationX = centerX - frameWidth / 2;
        int setLocationY = centerY - frameHeight / 2;

        this.setLocation(setLocationX, setLocationY);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nomText = new javax.swing.JTextField();
        prenomText = new javax.swing.JTextField();
        adresseText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmdpText = new javax.swing.JPasswordField();
        mdpText = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        checkpassword = new javax.swing.JCheckBox();
        mondoc = new javax.swing.JComboBox<>();
        docspec = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/turn-left.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 33));
        getContentPane().add(nomText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 155, -1));
        getContentPane().add(prenomText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 156, 155, -1));
        getContentPane().add(adresseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 155, -1));

        jLabel3.setText("Nom :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 113, -1, -1));

        jLabel4.setText("Prenom :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 159, -1, -1));

        jLabel5.setText("Adresse :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 203, -1, -1));

        jLabel6.setText("Mot de passe :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel7.setText("Confirmer mdp :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));
        getContentPane().add(cmdpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 120, -1));
        getContentPane().add(mdpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 120, -1));

        jLabel8.setText("E-mail :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 243, 47, -1));
        getContentPane().add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 155, -1));

        confirmButton.setBackground(new java.awt.Color(51, 153, 255));
        confirmButton.setText("Confirmer");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 92, 33));

        checkpassword.setText("check password");
        checkpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(checkpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 120, -1));

        getContentPane().add(mondoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 180, -1));

        docspec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cardiologue", "dentiste", "chirurgien général" }));
        docspec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                docspecItemStateChanged(evt);
            }
        });
        getContentPane().add(docspec, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 150, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/pat.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new SignIn().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed

       if(nomText.getText().isEmpty() || prenomText.getText().isEmpty() || adresseText.getText().isEmpty() || emailText.getText().isEmpty()
                || mdpText.getText().isEmpty() || cmdpText.getText().isEmpty() || docspec.getSelectedItem()==null ||mondoc.getSelectedItem()==null ){
            
            JOptionPane.showMessageDialog(null, "missing information !!! ");
            
        }
        else{
        try {
     con =  (Connection) connexion.getConnect();
    
    String Query = "SELECT COUNT(*) AS count FROM patient WHERE email = ?";
    PreparedStatement checkEmailStatement = (PreparedStatement) con.prepareStatement(Query);
    checkEmailStatement.setString(1, emailText.getText());
    ResultSet countResult = checkEmailStatement.executeQuery();
    countResult.next();
    int emailCount = countResult.getInt("count");

    if (emailCount > 0) {
        // Email already exists
        JOptionPane.showMessageDialog(null, "E-mail already used !!! ");
    }  else {

        String sql = "INSERT INTO patient (nom, prenom, adresse, email,docspec,mondoc, mdp, cmdp) VALUES (?, ?, ?, ?, ?, ?,?,?)";
        PreparedStatement statement = (PreparedStatement) con.prepareStatement(sql);

        statement.setString(1, nomText.getText());
        statement.setString(2, prenomText.getText());
        statement.setString(3, adresseText.getText());
        statement.setString(4, emailText.getText());
        statement.setString(5, docspec.getSelectedItem().toString());
        statement.setString(6, mondoc.getSelectedItem().toString());
        statement.setString(7, mdpText.getText());
        statement.setString(8, cmdpText.getText());
        

        statement.executeUpdate();
        JOptionPane.showMessageDialog(null, "Bien enregistré ");
    }
} catch (SQLException e) {
    e.printStackTrace();
}

        
        }

    }//GEN-LAST:event_confirmButtonActionPerformed

    private void checkpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkpasswordActionPerformed

        if(checkpassword.isSelected())
        {
            mdpText.setEchoChar((char)0);
            cmdpText.setEchoChar((char)0);
        }
        else {
            mdpText.setEchoChar('*');
            cmdpText.setEchoChar('*');
        }
    }//GEN-LAST:event_checkpasswordActionPerformed

    private void docspecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_docspecItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            // Clear the existing items in the second JComboBox
            mondoc.removeAllItems();

            try {
                con = (Connection) connexion.getConnect();
                String selectedSpecialite = docspec.getSelectedItem().toString();
                String sql = "SELECT nom,prenom FROM docteur WHERE specialite = ?";
                PreparedStatement statement = (PreparedStatement) con.prepareStatement(sql);
                statement.setString(1, selectedSpecialite);
                ResultSet resultSet = statement.executeQuery();

                // Populate the second JComboBox with doctor names for the selected specialty
                while (resultSet.next()) {
                    
                    mondoc.addItem(resultSet.getString("nom")+" "+resultSet.getString("prenom"));
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_docspecItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signInPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signInPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signInPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signInPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signInPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresseText;
    private javax.swing.JCheckBox checkpassword;
    private javax.swing.JPasswordField cmdpText;
    private javax.swing.JButton confirmButton;
    private javax.swing.JComboBox<String> docspec;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField mdpText;
    private javax.swing.JComboBox<String> mondoc;
    private javax.swing.JTextField nomText;
    private javax.swing.JTextField prenomText;
    // End of variables declaration//GEN-END:variables
}
