/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import com.mysql.jdbc.PreparedStatement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SBS
 */
public class signInDoctor extends javax.swing.JFrame {
    
    
    
    
    Connection con=null;
    PreparedStatement statement=null;
    ResultSet rs=null;
    /**
     * Creates new form signInDoctor
     */
    public signInDoctor() {
        initComponents();
        centerFrameOnScreen();
    }
private void centerFrameOnScreen() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int centerX = (int) screenSize.getWidth() / 2;
        int centerY = (int) screenSize.getHeight() / 2;

        int frameWidth = this.getSize().width;
        int frameHeight = this.getSize().height;

        int setLocationX = centerX - frameWidth / 2;
        int setLocationY = centerY - frameHeight / 2;

        this.setLocation(setLocationX, setLocationY);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nomText = new javax.swing.JTextField();
        prenomText = new javax.swing.JTextField();
        adresseText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmdpText = new javax.swing.JPasswordField();
        mdpText = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        specialiteCB = new javax.swing.JComboBox<>();
        checkpassword = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/turn-left.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 26, 28));
        getContentPane().add(nomText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 155, -1));
        getContentPane().add(prenomText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 156, 155, -1));
        getContentPane().add(adresseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 155, -1));

        jLabel3.setText("Nom :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 113, -1, -1));

        jLabel4.setText("Prenom :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 159, -1, -1));

        jLabel5.setText("Adresse :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 203, -1, -1));

        jLabel6.setText("Mot de passe :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel7.setText("Confirmer mdp :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));
        getContentPane().add(cmdpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 120, -1));
        getContentPane().add(mdpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 120, -1));

        jLabel8.setText("E-mail :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 243, 47, -1));
        getContentPane().add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 155, -1));

        confirmButton.setBackground(new java.awt.Color(51, 153, 255));
        confirmButton.setText("Confirmer");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 92, 33));

        jLabel1.setText("Specialité :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 285, -1, -1));

        specialiteCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cardiologue", "dentiste", "chirurgien général", " " }));
        getContentPane().add(specialiteCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 282, 157, -1));

        checkpassword.setText("check password");
        checkpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(checkpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 120, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/doctorr.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       new SignIn().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        
        if(nomText.getText().isEmpty() || prenomText.getText().isEmpty() || adresseText.getText().isEmpty() || emailText.getText().isEmpty()
                || mdpText.getText().isEmpty() || cmdpText.getText().isEmpty() || specialiteCB.getSelectedItem()==null){
            
            JOptionPane.showMessageDialog(null, "missing information !!! ");
            
        }
        else{
        try {
    con = connexion.getConnect();
    
    String checkEmailQuery = "SELECT COUNT(*) AS count FROM docteur WHERE email = ?";
    PreparedStatement checkEmailStatement = (PreparedStatement) con.prepareStatement(checkEmailQuery);
    checkEmailStatement.setString(1, emailText.getText());

    ResultSet countResult = checkEmailStatement.executeQuery();
    countResult.next();
    int emailCount = countResult.getInt("count");

    if (emailCount > 0) {
        // Email already exists
        JOptionPane.showMessageDialog(null, "E-mail already used !!! ");
    }  else {
        String sql = "INSERT INTO docteur (nom, prenom, adresse, email, mdp, cmdp, specialite) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement statement = (PreparedStatement) con.prepareStatement(sql);

        statement.setString(1, nomText.getText());
        statement.setString(2, prenomText.getText());
        statement.setString(3, adresseText.getText());
        statement.setString(4, emailText.getText());
        statement.setString(5, mdpText.getText());
        statement.setString(6, cmdpText.getText());
        statement.setString(7, specialiteCB.getSelectedItem().toString());

        statement.executeUpdate();
        JOptionPane.showMessageDialog(null, "Bien enregistré ");
    }
} catch (SQLException e) {
    e.printStackTrace();
}

        
        }
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void checkpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkpasswordActionPerformed
        
        
        if(checkpassword.isSelected())
        {
            mdpText.setEchoChar((char)0);
            cmdpText.setEchoChar((char)0);
        }
        else {
            mdpText.setEchoChar('*');
            cmdpText.setEchoChar('*');
        }

    }//GEN-LAST:event_checkpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signInDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signInDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signInDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signInDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signInDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresseText;
    private javax.swing.JCheckBox checkpassword;
    private javax.swing.JPasswordField cmdpText;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField mdpText;
    private javax.swing.JTextField nomText;
    private javax.swing.JTextField prenomText;
    private javax.swing.JComboBox<String> specialiteCB;
    // End of variables declaration//GEN-END:variables
}
